# travis.yml for github.com/hamzakhanvit/sam2sga

language: python

python:
  - 3.6

# Install python packages
install:
  - pip install gfapy pysam
  - python setup.py -q install
   
script:
  - pytest
