# travis.yml for github.com/hamzakhanvit/sam2gfa

language: python

python:
  - 3.6

# Install python packages
install:
  - pip install gfapy pysam simplesam numpy biopython
  - python setup.py -q install
   
script:
  - pytest
